# データセット設定
dataset:
  data_path: '/app/data/CASIA2'
  authentic_folder: 'Au'
  tampered_folder: 'Tp'
  image_size: [128, 128]
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  seed: 42

# 前処理設定
preprocessing:
  normalize: true
  color_space: 'YCrCb'
  channels:
    use_channels: ['Cr', 'Cb']
  
  # GLCM特徴量に関する詳細設定
  glcm:
    distances: [1, 2]
    angles: [0, 45, 90, 135] 
    levels: 16
    properties: ['contrast', 'homogeneity']

  # 残差特徴量に関する設定
  residual_features:
    methods: ['median', 'gaussian']

# モデル設定
model:
  in_channels: 7
  num_classes: 2

# 学習設定
training:
  epochs: 80
  batch_size: 8
  lr: 0.0005
  weight_decay: 0.001
  optimizer: 'Adam'
  model_save_path: './models/best_model_90.pth'